#!/bin/bash

function check-prerequisites {
	[ "" == "$(which kpartx)" ] && echo "please install kpartx" && exit 1
	[ "" == "$(which pv)" ] && echo "please install pv" && exit 1
	[ "" == "$(which qemu-arm-static)" ] && echo "please install qemu-arm-static" && exit 1
	[ "" == "$(which bmaptool)" ] && echo "please install bmaptool" && exit 1
}

function mount-ram-disk {
	if [ "" == "$(mount | grep ${RAM_DISK_DIR})" ]; then
		INFO "mounting ram disk: $(LIGHT_GREEN ${RAM_DISK_DIR})"
		[ ! -d "${RAM_DISK_DIR}" ] && mkdir -p ${RAM_DISK_DIR}
		mount -t tmpfs none ${RAM_DISK_DIR}
	else
		INFO "ram disk $(LIGHT_GREEN ${RAM_DISK_DIR}) is already mount"
	fi
}

function download-bbb-image {
	if [ ! -f "${BBB_IMAGE}" ]; then
		INFO "missing ${BBB_IMAGE}"
		wget -O ${BBB_IMAGE} ${BBB_IMAGE_URL} || exit 1
	else
		INFO "${BBB_IMAGE} exists"
	fi
}

function create-work-image {
	RUN_CMD_STREAMING rm -f ${WORK_IMAGE} || exit 1
	FILENAME=$(basename ${BBB_IMAGE})
	EXTENSION="${FILENAME#*.}"
	INFO "image file extension: ${EXTENSION}"

	INFO "copy bbb image to work image"
	unxz -c ${BBB_IMAGE} > ${WORK_IMAGE} || exit 1
	# unxz -c ${BBB_IMAGE} | pv > ${WORK_IMAGE} || exit 1

	if [ "true" == "${BMAP_DUMMY_OPT_SUPPORT}" ]; then
		INFO "dummy-run"
		RUN_CMD_STREAMING bmaptool create -o ${WORK_IMAGE}.bmap ${WORK_IMAGE}
		RUN_CMD_STREAMING bmaptool copy --bmap ${WORK_IMAGE}.bmap --dummy ${WORK_IMAGE} /dev/null
	fi
}

function mount-work-image {
	TMP=$(mktemp /tmp/XXXXXX)
	kpartx -d -s -v ${WORK_IMAGE}
	kpartx -a -s -v ${WORK_IMAGE} > ${TMP} 2>&1
	[ "0" != "$?" ] && ERR "failed to mount ${WORK_IMAGE}" && cat ${TMP} && exit 1
	export WORK_DEVICE="/dev/mapper/$(cat ${TMP} | tail -n1 | awk '{print $3}')"
	INFO "working device: $(LIGHT_GREEN ${WORK_DEVICE})"

	mount | grep "/mnt/bbb-rootfs" | awk '{print $1}' | xargs -I{} sh -c "umount {}"
	[ ! -d "${WORK_ROOTFS_DIR}" ] && RUN_CMD_STREAMING mkdir -p ${WORK_ROOTFS_DIR}
	RUN_CMD_STREAMING mount -t ext4 ${WORK_DEVICE} ${WORK_ROOTFS_DIR}
	INFO "working rootfs: $(LIGHT_GREEN ${WORK_ROOTFS_DIR})"
}

function pre-rootfs {
	RUN_CMD_STREAMING cp $(which qemu-arm-static) ${WORK_ROOTFS_DIR}/usr/bin
	RUN_CMD_STREAMING mount -o bind /tmp ${WORK_ROOTFS_DIR}/tmp
	RUN_CMD_STREAMING mount -o bind /dev ${WORK_ROOTFS_DIR}/dev
	RUN_CMD_STREAMING mount -o bind /proc ${WORK_ROOTFS_DIR}/proc
	RUN_CMD_STREAMING mount -o bind /sys ${WORK_ROOTFS_DIR}/sys
	RUN_CMD_STREAMING mv ${WORK_ROOTFS_DIR}/etc/resolv.conf ${WORK_ROOTFS_DIR}/etc/resolv.conf.bak
	echo "nameserver 8.8.8.8" > ${WORK_ROOTFS_DIR}/etc/resolv.conf
	mkdir /tmp/bash-utils
	cp $(dirname $0)/externals/bash-utils/system /tmp/bash-utils/

	# This registers the static QEMU we copied as arm-interpreter to the kernel.
	#
	echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' > /proc/sys/fs/binfmt_misc/register

	RUN_CMD_STREAMING wget -q -O /tmp/repos.rcn-ee.net.gpg.key http://repos.rcn-ee.net/ubuntu/conf/repos.rcn-ee.net.gpg.key
}

function run-chroot-cmd {
	INFO "$(LIGHT_GREEN $@)"
	chroot ${WORK_ROOTFS_DIR} /bin/bash -c "$@"
}

function process-rootfs {
	TMPDIR="/tmp"
	if [ ! -d "${TMPDIR}/dotfiles" ]; then
		INFO "dotfiles: downloading from github"
		git clone -q https://github.com/yagamy4680/dotfiles.git ${TMPDIR}/dotfiles
		cd ${TMPDIR}/dotfiles
		INFO "dotfiles: init sub-module"
		git submodule init -q
		INFO "dotfiles: update sub-module"
		git submodule update -q
		touch ${TMPDIR}/dotfiles/.bootstrapped
	fi
	cat apt-packages.conf | grep -v "^#" | sed 's/^ *$//g' | grep -v "^$" | sort > /tmp/apt-packages.conf
	INFO "dotfiles: copying from ${TMPDIR}/dotfiles to ${WORK_ROOTFS_DIR}/opt"
	cp -R ${TMPDIR}/dotfiles ${WORK_ROOTFS_DIR}/opt
	run-chroot-cmd "apt-key add /tmp/repos.rcn-ee.net.gpg.key"
	run-chroot-cmd "apt-get update -q"
	run-chroot-cmd "apt-get -q -y install python3-pip $(cat /tmp/apt-packages.conf | tr '\n' ' ')"
	run-chroot-cmd "pip3 install -q $(cat ${CURRENT}/pip3-packages.conf | tr '\n' ' ')"
	run-chroot-cmd "echo 'Asia/Tokyo' > /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata"
	run-chroot-cmd "apt-get remove apache2 -y && apt-get purge apache2 -y"
	run-chroot-cmd "update-rc.d udhcpd disable"
	run-chroot-cmd "update-rc.d pppd-dns disable"
	run-chroot-cmd "cd /opt/dotfiles && ./bootstrap"
	run-chroot-cmd "source /tmp/bash-utils/system && generate_os_variable_dump"
	# chroot ${WORK_ROOTFS_DIR} /bin/bash
	run-chroot-cmd "apt-get clean -y -q && apt-get autoclean -y -q && find /var/lib/apt -type f | xargs rm -f"
	run-chroot-cmd "rm -rf /var/tmp/*"
	# chroot ${WORK_ROOTFS_DIR} /bin/bash
}

function post-rootfs {
	# zero-fill will make bmaptool think all blocks are occupied, so
	# this size optimization shall not be used.
	#
	# RUN_CMD_STREAMING dd if=/dev/zero of=${WORK_ROOTFS_DIR}/EMPTY bs=1M 
	# RUN_CMD_STREAMING rm -f ${WORK_ROOTFS_DIR}/EMPTY
	find ${WORK_ROOTFS_DIR}/var/log -type f | while read f; do echo -ne '' > $f; done;
	RUN_CMD_STREAMING rm -rf /var/tmp/*
	RUN_CMD_STREAMING sync
	RUN_CMD_STREAMING sync
	RUN_CMD_STREAMING sleep 2
	RUN_CMD_STREAMING rm -f ${WORK_ROOTFS_DIR}/etc/resolv.conf
	RUN_CMD_STREAMING mv ${WORK_ROOTFS_DIR}/etc/resolv.conf.bak ${WORK_ROOTFS_DIR}/etc/resolv.conf
	RUN_CMD_STREAMING umount ${WORK_ROOTFS_DIR}/dev && sync
	RUN_CMD_STREAMING umount ${WORK_ROOTFS_DIR}/proc && sync
	RUN_CMD_STREAMING umount ${WORK_ROOTFS_DIR}/sys && sync
	RUN_CMD_STREAMING umount ${WORK_ROOTFS_DIR}/tmp && sync
	rm -f /tmp/repos.rcn-ee.net.gpg.key
}

function umount-image {
	RUN_CMD_STREAMING sync
	RUN_CMD_STREAMING sync
	RUN_CMD_STREAMING sleep 2
	RUN_CMD_STREAMING umount ${WORK_ROOTFS_DIR}
	RUN_CMD_STREAMING sync
	RUN_CMD_STREAMING sync
	RUN_CMD_STREAMING sleep 2
	RUN_CMD_STREAMING kpartx -d -v ${WORK_IMAGE}
}

function generate-image-bmap {
	RUN_CMD_STREAMING sync
	RUN_CMD_STREAMING sleep 2
	RUN_CMD_STREAMING bmaptool create -o ${WORK_IMAGE}.bmap ${WORK_IMAGE}

	if [ "true" == "${BMAP_DUMMY_OPT_SUPPORT}" ]; then
		INFO "dummy run"
		RUN_CMD_STREAMING bmaptool copy --bmap ${WORK_IMAGE}.bmap --dummy ${WORK_IMAGE} /dev/null
	fi
}

function init-variables {
	[ "" == "${RAM_DISK_DIR}" ] && export RAM_DISK_DIR="/tmp/tmpfs"
	[ "" == "${BBB_IMAGE_URL}" ] && export BBB_IMAGE_URL="https://rcn-ee.com/rootfs/2015-10-09/microsd/bone-ubuntu-14.04.3-console-armhf-2015-10-09-2gb.img.xz"
	export CURRENT=$(pwd)
	cd $(dirname $0)
	export BASEDIR=$(pwd)
	cd ${CURRENT}

	export BBB_IMAGE="/tmp/$(basename ${BBB_IMAGE_URL})"
	export WORK_IMAGE="${RAM_DISK_DIR}/work-image.bin"
	export WORK_ROOTFS_DIR="/mnt/bbb-rootfs"
	[ "" == "${BMAP_DUMMY_OPT_SUPPORT}" ] && export BMAP_DUMMY_OPT_SUPPORT="false"
}


check-prerequisites

source $(dirname $0)/externals/bash-utils/verbose
source $(dirname $0)/externals/bash-utils/funcs
init-verbose $0
init-variables

mount-ram-disk
download-bbb-image
create-work-image

mount-work-image
pre-rootfs
process-rootfs
post-rootfs
umount-image

generate-image-bmap
