#!/bin/bash
#

function dump_versions {
	local CSV_FILE="/tmp/pkg-versions.csv"
	rm -f ${CSV_FILE}

	echo -e "type\tpackage\tversion" >> ${CSV_FILE}

	# Debian packages and their versions
	#
	dpkg-query -l | grep "^..\ \ " | awk '{printf "debian\t%s\t%s\n", $2, $3}' >> ${CSV_FILE}

	# Python2 packages and their versions
	#
	pip freeze | awk -F'==' '{printf "python2\t%s\t%s\n", $1, $2}' >> ${CSV_FILE}

	# Python3 packages and their versions
	#
	pip3 freeze | awk -F'==' '{printf "python3\t%s\t%s\n", $1, $2}' >> ${CSV_FILE}
}

dump_versions $@
